import type { AnatomyPlan, LandmarkPose } from './AnatomyPlan';
const pose = (
  points: Record<keyof LandmarkPose, [number, number]>,
): LandmarkPose =>
  Object.fromEntries(
    Object.entries(points).map(([name, [x, y]]) => [name, { x, y }]),
  ) as LandmarkPose;
/** Phase 0 design target. Never silently installed as production art or a rig. */
export const DAN_ANATOMY: AnatomyPlan = {
  id: 'dan',
  revision: 1,
  status: 'landmark-proposal',
  coordinates: 'character-local-y-down',
  sideConvention: 'image-left-right',
  setup: pose({
    root: [0, 0],
    pelvis: [0, -180],
    spine_lower: [0, -209],
    spine_mid: [0, -237],
    chest: [0, -269],
    neck: [0, -311],
    head: [1, -343],
    crown: [1, -372],
    clavicle_L: [-9, -301],
    shoulder_L: [-40, -287],
    elbow_L: [-56, -222],
    wrist_L: [-67, -155],
    hand_L: [-69, -139],
    clavicle_R: [9, -301],
    shoulder_R: [40, -287],
    elbow_R: [56, -222],
    wrist_R: [67, -155],
    hand_R: [69, -139],
    hip_L: [-18, -180],
    knee_L: [-27, -96],
    ankle_L: [-35, -12],
    heel_L: [-29, 0],
    toe_L: [-47, 0],
    hip_R: [18, -180],
    knee_R: [27, -96],
    ankle_R: [35, -12],
    heel_R: [29, 0],
    toe_R: [47, 0],
  }),
  idle: pose({
    root: [0, 0],
    pelvis: [-12, -180],
    spine_lower: [-10, -209],
    spine_mid: [-6, -237],
    chest: [-4, -269],
    neck: [-3, -311],
    head: [0, -343],
    crown: [1, -372],
    clavicle_L: [-13, -299],
    shoulder_L: [-43, -285],
    elbow_L: [-48, -218],
    wrist_L: [-45, -150],
    hand_L: [-44, -134],
    clavicle_R: [5, -302],
    shoulder_R: [36, -289],
    elbow_R: [40, -222],
    wrist_R: [35, -155],
    hand_R: [33, -139],
    hip_L: [-30, -182],
    knee_L: [-33, -97],
    ankle_L: [-35, -12],
    heel_L: [-29, 0],
    toe_L: [-47, 0],
    hip_R: [6, -178],
    knee_R: [27, -96],
    ankle_R: [41, -12],
    heel_R: [35, 0],
    toe_R: [53, 0],
  }),
  support: 'L',
  targetSupportShare: [0.6, 0.7],
  sockets: {
    throwingHand: 'hand_R',
    offHand: 'hand_L',
    head: 'head',
    chest: 'chest',
    waist: 'pelvis',
    footL: 'heel_L',
    footR: 'heel_R',
  },
  notes: [
    'Setup separation is for authoring; idle is a distinct asymmetric pose.',
    'Clavicles branch from chest. Hip sockets branch from pelvis, inside the shorts.',
    'Support hip shifts over image-left foot; chest and head counterbalance with a shallow spinal curve.',
    'The right knee relaxes; foot rotation must be authored with matching drawing, not inferred from a screen-space bone.',
    'Hand landmarks end at a relaxed palm; curled finger attachments and clothing weights still require source fitting.',
    'This is a geometry proposal pending visual validation, not a completed or licensed Spine export.',
  ],
};
