'use client';
import {useRef,useState} from 'react';
import {Upload,ArrowUpRight,Check,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {PACK_LIMIT,validateCharacterPack,type CharacterPack} from '@/lib/arena/character-pack';
import {verifyPackImages,installCharacterPack,packConflict} from '@/lib/arena/character-store';
import {POSE_NAMES} from '@/lib/arena/paper';

const names:Record<string,string>={ready:'Ready', 'underarm-backswing':'Backswing','underarm-release':'Release','football-cocked':'Football','basketball-shot':'Basketball',celebrate:'Celebrate'};
export default function CharacterInstaller({onInstalled}:{onInstalled:(id:string)=>void}){
 const [open,setOpen]=useState(false),[pack,setPack]=useState<CharacterPack|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const input=useRef<HTMLInputElement>(null),request=useRef(0);
 const read=async(file:File)=>{const ticket=++request.current;setPack(null);setError('');setBusy(true);setMessage('Checking the card, six poses and alignment…');try{if(file.size>PACK_LIMIT)throw Error('Choose a character pack under 40 MB.');const p=validateCharacterPack(JSON.parse(await file.text()));await verifyPackImages(p);const conflict=packConflict(p);if(conflict)throw Error(conflict);if(ticket!==request.current)return;setPack(p);setMessage(p.manifest.puppet?'Articulated character, movement tracks and fallback poses checked. Ready to install.':'All six poses checked. Ready to install.');}catch(e){if(ticket!==request.current)return;setMessage('');setError(e instanceof SyntaxError?'Choose the .arena-character.json file from Codex, not the original card image.':e instanceof Error?e.message:String(e));}finally{if(ticket===request.current)setBusy(false);}};
 const install=async()=>{if(!pack)return;setBusy(true);setError('');setMessage('Saving your character…');try{const p=await installCharacterPack(pack);onInstalled(p.card.id);setOpen(false);setPack(null);setMessage('');}catch(e){setError(e instanceof Error?e.message:String(e));setMessage('');}finally{setBusy(false);}};
 return <><Button className="primary-cta add-character" onClick={()=>setOpen(true)}><Upload size={18}/>Install character</Button><Dialog open={open} onOpenChange={v=>{if(busy)return;setOpen(v);}}><DialogContent className="info-dialog character-installer"><DialogHeader><DialogTitle>FROM CARD TO COURT.</DialogTitle><DialogDescription>Install the finished character pack from your Codex chat.</DialogDescription></DialogHeader>
 {!pack&&<div className="character-workflow"><span className="eyebrow">MAKE YOUR NEXT COMPETITOR</span><p>Upload a card in Codex and say:</p><blockquote>“Make this card an arena character.”</blockquote><p>Codex creates the cutout poses, fits the animations and returns one file. Bring that finished pack here.</p></div>}
 <input ref={input} className="sr-only" type="file" accept=".json,application/json" aria-label="Character pack file" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void read(file);e.target.value='';}}/>
 {!pack&&<button className="character-drop" disabled={busy} onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&e.dataTransfer.files[0])void read(e.dataTransfer.files[0]);}}><Upload size={28}/><strong>Choose character pack</strong><span>or drop the .arena-character.json file here</span></button>}
 {pack&&<div className="character-pack-review"><div className="pack-identity"><img src={pack.files['card.png'].data} alt={pack.card.name+' original card'}/><div><span className="eyebrow">YOUR NEXT COMPETITOR</span><h2>{pack.card.name}</h2><p>{pack.card.description}</p><span className="pack-ready"><Check size={16}/> Four Watch sports · {pack.manifest.puppet?'Articulated movement':'Six poses'} · {pack.manifest.puppet?.joined?'Ready for Play':'Watch only, not Play'}</span></div></div><div className="pack-poses">{POSE_NAMES.map(p=><figure key={p}><div><img src={pack.files[p+'.png'].data} alt={pack.card.name+' '+names[p]+' pose'}/></div><figcaption>{names[p]}</figcaption></figure>)}</div><div className="pack-actions"><Button variant="outline" disabled={busy} onClick={()=>input.current?.click()}>Choose another pack</Button><Button className="primary-cta" disabled={busy} onClick={install}>Install & preview <ArrowUpRight size={18}/></Button></div></div>}
 {message&&<p className="pack-status" role="status">{busy?<LoaderCircle size={17} className="pack-spinner"/>:<Check size={17}/>} {message}</p>}{error&&<p className="pack-error" role="alert">{error}</p>}
 <p className="quiet-note">Installed characters stay in this browser. Keep the pack to install on another device. The original card stays intact.</p>
 </DialogContent></Dialog></>;
}
