'use client';
import {useState,useRef,useEffect,useCallback} from 'react';
import {ArrowUpRight,Play,Pause,SkipForward,RotateCcw,Volume2,VolumeX,Trophy,Settings2,History,ChevronRight,Info,Maximize2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import ArenaStage from './ArenaStage';
import SetupDialog from './SetupDialog';
import Panels from './Panels';
import SecondaryViews from './SecondaryViews';
import {PlaybackClock} from '@/lib/arena/clock';
import {ArenaAudio} from '@/lib/arena/audio';
import {COPIES,SPORTS,EVENTS,DEFAULT_POLICY,cardById,userById,type Sport,type Recording,type SavedState,type Strategy,type Setup,type Policy,type Clip} from '@/lib/arena/model';
import {LocalArenaRepository,standings,availableEntry,rankedPlayed,awardsFor} from '@/lib/arena/persistence';
import {RULES_VERSION,revealed} from '@/lib/arena/simulation';
import {manifest} from '@/lib/arena/assets';
import {createDemoServices,type ArenaServices} from '@/lib/arena/adapters';
export default function Game(){
 const [view,setView]=useState('play'),[sport,setSport]=useState<Sport>('cornhole'),[user,setUser]=useState('user-doug'),[opponent,setOpponent]=useState('user-jules'),[ownCard,setOwnCard]=useState('card-mack'),[oppCard,setOppCard]=useState('card-marmalade'),[strategy,setStrategy]=useState<Strategy>('steady'),[mode,setMode]=useState('exhibition'),[tie,setTie]=useState('draw'),[secret,setSecret]=useState(false),[showcase,setShowcase]=useState(true),[setupOpen,setSetupOpen]=useState(false),[panel,setPanel]=useState<string|null>(null),[state,setState]=useState<SavedState|null>(null),[rec,setRec]=useState<Recording|null>(null),[time,setTime]=useState(0),[paused,setPaused]=useState(false),[speed,setSpeed]=useState(1),[sound,setSound]=useState(false),[reduced,setReduced]=useState(false),[low,setLow]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[profile,setProfile]=useState<string|null>(null),[previewCard,setPreviewCard]=useState('card-mack'),[previewClip,setPreviewClip]=useState<Clip>('idle'),[importText,setImportText]=useState(''),[importStatus,setImportStatus]=useState(''),[draftPolicy,setDraftPolicy]=useState<Policy>({...DEFAULT_POLICY}),[metrics,setMetrics]=useState<any>(null),[clean,setClean]=useState(false);
 const services=useRef<ArenaServices|null>(null);
 const clock=useRef<PlaybackClock|null>(null);if(!clock.current)clock.current=new PlaybackClock();const audio=useRef<ArenaAudio|null>(null);if(!audio.current)audio.current=new ArenaAudio();const repository=useRef<LocalArenaRepository|null>(null),pendingAuto=useRef(false),startGuard=useRef(false),lastCue=useRef(''),lastSave=useRef(0),recRef=useRef(rec);recRef.current=rec;
 useEffect(()=>{services.current=createDemoServices(localStorage);repository.current=services.current.results as LocalArenaRepository;try{const s=repository.current.load();setState(s);setDraftPolicy({...s.policy});}catch(e){setError(String(e));}setReduced(matchMedia('(prefers-reduced-motion: reduce)').matches);let prior=0;const unsub=clock.current!.subscribe(t=>{if(Math.abs(t-prior)>.045||t>=clock.current!.duration){setTime(t);prior=t;}const r=recRef.current;if(r&&Math.abs(t-lastSave.current)>2){lastSave.current=t;try{repository.current?.savePlayback(r.id,t);}catch{setError('Playback could not be saved. Keep this tab open and export your recording.');}}});const hide=()=>{if(recRef.current)repository.current?.savePlayback(recRef.current.id,clock.current!.time);};addEventListener('pagehide',hide);const onStorage=()=>{try{setState(repository.current!.load());}catch{}};addEventListener('storage',onStorage);return()=>{unsub();clock.current!.stop();audio.current!.destroy();removeEventListener('pagehide',hide);removeEventListener('storage',onStorage);};},[]);
 const status=rec?revealed(rec,time):null,complete=!!status?.complete,hiddenId=rec?(complete?null:rec.id):state?.active?.id,displayState=state&&hiddenId?{...state,ledger:state.ledger.filter(a=>a.contestId!==hiddenId),recordings:state.recordings.filter(r=>r.id!==hiddenId)}:state,table=displayState?standings(displayState):[],myRow=table.find(r=>r.user.id===user),entry=state?availableEntry(state,user,sport):undefined,playing=!!rec&&!complete;
 const selectedCards:[string,string]=rec?[rec.setup.participants[0].cardId,rec.setup.participants[1].cardId]:[ownCard,oppCard];
 useEffect(()=>{if(!rec)return;let cue='';let kind:'summon'|'release'|'score'|'miss'|'victory'='summon';if(time<9)cue='intro'+Math.floor(time/3.7);if(status?.current){const a=status.current;if(time>=a.contactAt){cue='contact'+a.index;kind=a.score?'score':'miss';}else if(time>=a.releaseAt){cue='release'+a.index;kind='release';}}if(complete){cue='victory';kind='victory';}if(cue&&cue!==lastCue.current){lastCue.current=cue;audio.current!.cue(kind);}},[rec,time,complete]);
 const stageReady=useCallback(()=>{setReady(true);if(pendingAuto.current){pendingAuto.current=false;clock.current!.paused=false;setPaused(false);}},[]),stageError=useCallback((e:string)=>setError(e),[]),metricsReady=useCallback((m:any)=>setMetrics(m),[]);
 const backToLobby=()=>{audio.current!.stop();if(rec)repository.current?.savePlayback(rec.id,time);setRec(null);setTime(0);clock.current!.start(0,Infinity);setPaused(false);setState(repository.current!.load());setView('play');};
 const replay=(r:Recording,resume=0)=>{audio.current!.stop();lastCue.current='';setPanel(null);setView('play');setSport(r.setup.sport);setRec(r);setTime(resume);setReady(false);pendingAuto.current=resume===0;clock.current!.start(resume,r.duration);clock.current!.paused=r.id!==rec?.id||resume!==0;setPaused(clock.current!.paused);setSpeed(1);clock.current!.speed=1;};
 const start=async()=>{if(startGuard.current||!repository.current)return;startGuard.current=true;setBusy(true);setError('');try{const ranked=mode==='ranked';if(ranked&&!entry)throw Error('No counted entry remains for this event. Choose Exhibition.');const users=ranked?entry!.users:[user,opponent];await services.current!.identity.select(user);const owned=(await Promise.all(users.map(uid=>services.current!.ownership.list(uid)))).flat();const participants=users.map(uid=>{const isMe=uid===user;const cardId=isMe?ownCard:(ranked?'card-marmalade':oppCard);const copy=owned.find(c=>c.userId===uid&&c.cardId===cardId);if(!copy)throw Error('No owned copy is available for this competitor.');return{userId:uid,copyId:copy.id,cardId,strategy:isMe?strategy:'steady' as Strategy};}) as Setup['participants'];const setup:Setup={id:ranked?'contest-'+entry!.id:crypto.randomUUID(),seed:ranked?entry!.seed:showcase&&sport==='cornhole'?'velvet-paw-29':crypto.randomUUID(),sport,participants,mode:ranked?'ranked':'exhibition',tie:tie==='paired'?'paired':'draw',secret:ranked?false:secret,showcase:!ranked&&showcase&&sport==='cornhole',entryId:ranked?entry!.id:undefined,policy:{...state!.policy},rulesVersion:RULES_VERSION,createdAt:new Date().toISOString()};const result=await repository.current.commit(setup);setState(result.state);setSetupOpen(false);replay(result.recording);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);startGuard.current=false;}};
 const pause=()=>{clock.current!.paused=!clock.current!.paused;setPaused(clock.current!.paused);if(clock.current!.paused)audio.current!.stop();};
 const skip=()=>{if(!rec)return;audio.current!.stop();clock.current!.seek(rec.duration);setTime(rec.duration);repository.current?.savePlayback(rec.id,rec.duration);setState(repository.current!.load());};
 const navigate=(to:string)=>{if(playing){clock.current!.paused=true;setPaused(true);audio.current!.stop();}setView(to);};
 const exportData=(data:unknown,name:string)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
 const webState=useRef<any>(null);webState.current={sport,score:status?.scores??[0,0],complete,rec,table};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'read_arena',description:'Read the current revealed score and leaderboard.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const p=webState.current;return{event:p.sport,score:p.score,complete:p.complete,leaderboard:p.table.map((r:any)=>({user:r.user.name,points:r.points,rank:r.rank}))};}},{name:'configure_arena_event',description:'Select a lobby event. Does not start or award a contest.',inputSchema:{type:'object',properties:{event:{type:'string',enum:SPORTS}},required:['event'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!SPORTS.includes(input?.event))throw Error('Choose a supported event.');if(webState.current.rec)throw Error('Return to the lobby before configuring a contest.');setSport(input.event);setView('play');return{selectedEvent:input.event};}}];for(const tool of tools)Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 const common={sport,setSport,mode,setMode,user,setUser,opponent,setOpponent,ownCard,setOwnCard,oppCard,setOppCard,strategy,setStrategy,tie,setTie,secret,setSecret,showcase,setShowcase,entry,state,setState,busy,error,start};
 const panelProps={panel,setPanel,state:displayState,setState,sport,user,rec,status,table,profile,replay,exportData,reduced,setReduced,low,setLow,draftPolicy,setDraftPolicy,metrics,repository,clock,audio,setRec,setError,previewCard,importText,setImportText,importStatus,setImportStatus};
 return <main className={'club-shell '+(clean?'spectator-clean':'')+(complete?' completed':'')}><header className="club-header"><a className="brand" href="/" onClick={e=>{e.preventDefault();backToLobby();}}>WYBMH<span>ARENA</span></a><nav aria-label="Main"><button className={view==='play'?'active':''} onClick={()=>navigate('play')}>Play</button><button className={view==='standings'?'active':''} onClick={()=>navigate('standings')}>Standings</button><button className={view==='collection'?'active':''} onClick={()=>navigate('collection')}>The collection</button></nav><div className="header-tools"><span className="local-label">LOCAL DEMO <i/></span><button className="icon-button" aria-label="Clubhouse settings" onClick={()=>setPanel('settings')}><Settings2 size={18}/></button></div></header>
 {view==='play'&&<><section className="lobby-title"><div><p className="eyebrow">THE AFTER HOURS ATHLETIC CLUB</p><h1>{rec?<>{EVENTS[sport].short}.<br/><em>{complete?'The clubhouse has spoken.':'Let the cards do the talking.'}</em></>:<>Everybody’s a legend.<br/><em>Until the cat shows up.</em></>}</h1></div><button className="standing-chip" onClick={()=>{setProfile(user);setPanel('user');}}><Trophy size={19}/><div><strong>{myRow?.points??0} points <span className="rank-inline">/ rank {myRow?.rank??'—'}</span></strong><span>{userById(user).name} · {state?Math.max(0,state.policy.allowance-rankedPlayed(state,user)):'—'} counted entries left</span></div><ChevronRight size={16}/></button></section>
 {!rec&&state?.active&&<div className="resume-banner"><span>Your last showdown is saved at {Math.floor(state.active.time)} seconds.</span><Button variant="outline" onClick={()=>{const r=state.recordings.find(r=>r.id===state.active!.id);if(r)replay(r,state.active!.time);}}>Resume contest <Play size={14}/></Button></div>}
 <section className={'club-stage '+(rec?'in-contest':'')} aria-label="The Clubhouse arena"><ArenaStage sport={sport} recording={rec} clock={clock.current} cards={selectedCards} reduced={reduced} low={low} onReady={stageReady} onError={stageError} onMetrics={metricsReady} imported={state?.imports}/><div className="stage-top"><span><i/> THE CLUBHOUSE · OPEN LATE</span><div className="stage-controls"><button aria-label={sound?'Mute sound':'Enable sound'} onClick={async()=>setSound(await audio.current!.toggle())}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button aria-label="Clean spectator view" onClick={()=>setClean(!clean)}><Maximize2 size={17}/></button></div></div>
 {!rec&&<div className="stage-event-label"><span>TONIGHT’S MAIN EVENT</span><h2>{EVENTS[sport].name}</h2><p>{EVENTS[sport].attempts} {EVENTS[sport].unit} each · Fully automatic</p></div>}
 {rec&&<div className="scoreboard" aria-label="Live score">{rec.setup.participants.map((p,i)=><div key={i} className={status?.current?.actor===i?'actor':''}><span>{cardById(p.cardId).name}</span><strong>{status?.scores[i]??0}</strong><small>{status?.contacts.filter(a=>a.actor===i).length??0}/{rec.attempts.filter(a=>a.actor===i).length} attempts</small></div>)}<span className="scoreboard-event">{EVENTS[sport].name}<small>{rec.setup.mode==='ranked'?'COUNTED ENTRY':'EXHIBITION · NO POINTS'}</small></span></div>}
 <div className="stage-bottom">{rec?<><span>{time<9?'THE CARDS ARE OPENING':complete?'FINAL SCORE':`ROUND ${(status?.current?.round??0)+1}`}</span><span>{status?.current?.special?'BLACKLIGHT BLOOM · COSMETIC':paused?'PAUSED':complete?'THAT’S A WRAP':'LIVE'}</span><span>{rec.setup.participants.map(p=>userById(p.userId).name).join(' vs ')}</span></>:<><span>0{SPORTS.indexOf(sport)+1} / 04</span><span>FRIENDS. PETS. QUESTIONABLE LEGENDS.</span><span>EST. {Math.round(14+EVENTS[sport].attempts*10.6)} SECONDS</span></>}</div></section>
 {error&&<div className="error-box" role="alert">{error}<button onClick={()=>{setError('');if(rec)replay(rec,time);else setLow(!low);}}>Restore arena</button></div>}
 {rec?<><div className="broadcast-strip"><p aria-live="polite" aria-atomic="true">{time<9?'From the collection to the clubhouse. Make some room.':complete?rec.winner===null?'A shared result. The rivalry continues.':cardById(rec.setup.participants[rec.winner].cardId).name+' takes the clubhouse.':status?.current&&time>=status.current.contactAt?status.current.commentary:status?.current?cardById(rec.setup.participants[status.current.actor].cardId).name+' lines up the next '+(sport==='basketball'?'shot':'throw')+'.':'A moment to settle. The contest continues.'}</p><div className="playback-controls"><button className="icon-button" aria-label={paused?'Resume playback':'Pause playback'} onClick={pause}>{paused?<Play size={18}/>:<Pause size={18}/>}</button><button className="speed-button" onClick={()=>{const next=speed===1?2:speed===2?.5:1;setSpeed(next);clock.current!.speed=next;}} aria-label="Playback speed">{speed}×</button>{time<9&&<button onClick={()=>{clock.current!.seek(9);setTime(9);}}>Skip entrance</button>}<button className="icon-button" aria-label="Skip to result" onClick={skip}><SkipForward size={19}/></button><button className="icon-button" aria-label="Attempt history" onClick={()=>setPanel('attempts')}><History size={18}/></button></div></div><div className="playback-progress" role="progressbar" aria-valuenow={Math.round(time/rec.duration*100)} aria-valuemin={0} aria-valuemax={100} aria-label="Contest playback"><span style={{width:Math.min(100,time/rec.duration*100)+'%'}}/></div>
 {complete?<section className="result-panel"><div><p className="eyebrow">{rec.setup.mode==='ranked'?'POINTS POSTED · ONCE PER ENTRY':'EXHIBITION · NO LEADERBOARD POINTS'}</p><h2>{rec.winner===null?'Honors shared.':cardById(rec.setup.participants[rec.winner].cardId).name+' wins.'}</h2><p>{rec.scores[0]} — {rec.scores[1]} <span>{EVENTS[sport].name}{rec.unresolvedDraw?' · Still tied after three extra pairs':''}</span></p></div><div className="result-awards">{rec.setup.participants.map(p=>{const row=table.find(r=>r.user.id===p.userId),award=awardsFor(rec).find(a=>a.userId===p.userId);const before=state?standings({...state,ledger:state.ledger.filter(a=>a.contestId!==rec.id)}).find(r=>r.user.id===p.userId):null;return <div key={p.userId}><span>{userById(p.userId).name}</span><strong>+{award?.delta??0}<small> points</small></strong><span>{row?.points??0} total · rank {row?.rank??'—'}{award&&before&&before.rank!==row?.rank?' (was '+before.rank+')':''}</span></div>})}</div><div className="result-actions"><Button className="primary-cta" onClick={backToLobby}>Back to the clubhouse <ArrowUpRight size={18}/></Button><button onClick={()=>replay(rec)}><RotateCcw size={15}/> Replay same recording</button></div></section>:<div className="card-rail">{rec.setup.participants.map((p,i)=><span key={p.copyId}><img src={'/assets/'+cardById(p.cardId).asset+'/head.png'} alt=""/>{cardById(p.cardId).name}<small>{p.strategy} · {i===0?'first':'second'}</small></span>)}<button onClick={()=>setPanel('rules')}>Arcade rules <Info size={14}/></button></div>}
 </>:<section className="entry-strip"><div><p className="eyebrow">CHOOSE YOUR EVENT</p><div className="event-buttons">{SPORTS.map((e,i)=><button aria-pressed={sport===e} className={sport===e?'selected':''} key={e} onClick={()=>setSport(e)}><span>0{i+1}</span>{EVENTS[e].name}</button>)}</div></div><Button className="primary-cta" disabled={!state} onClick={()=>setSetupOpen(true)}>Choose competitors <ArrowUpRight size={20}/></Button></section>}</>}
 {view!=='play'&&<SecondaryViews {...{view,state:displayState,filter,setFilter,user,setProfile,setPanel,previewCard,setPreviewCard,previewClip,setPreviewClip,clock,sport,reduced,low,stageReady,stageError,setImportText}}/>}
 <footer><span>Will You Be My Hero? — Arena</span><div><button onClick={()=>setPanel('rules')}>House rules</button><button onClick={()=>setPanel('history')}>History</button><span>Sound {sound?'on':'off'}</span></div></footer>
 <SetupDialog {...common} open={setupOpen} setOpen={setSetupOpen}/><Panels {...panelProps}/></main>;
}





