'use client';
import {useState,useRef,useEffect,useCallback} from 'react';
import {ArrowUpRight,Play,Pause,SkipForward,RotateCcw,Volume2,VolumeX,Trophy,Settings2,History,ChevronRight,Info,Maximize2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import ArenaStage from './ArenaStage';
import SetupDialog from './SetupDialog';
import Panels from './Panels';
import SecondaryViews from './SecondaryViews';
import PlayableArena from './live/PlayableArena';
import {PlaybackClock} from '@/lib/arena/clock';
import {matchNarration} from '@/lib/arena/engine/core/MatchNarration';
import {ArenaAudio} from '@/lib/arena/audio';
import {COPIES,SPORTS,EVENTS,DEFAULT_POLICY,cardById,userById,type Sport,type Recording,type SavedState,type Strategy,type Setup,type Policy,type Clip} from '@/lib/arena/model';
import {LocalArenaRepository,standings,availableEntry,rankedPlayed,awardsFor} from '@/lib/arena/persistence';
import {RULES_VERSION,revealed} from '@/lib/arena/simulation';
import {TIMING,matchEstimate,scoreTime} from '@/lib/arena/match-timeline';
import {manifest} from '@/lib/arena/assets';
import {createDemoServices,type ArenaServices} from '@/lib/arena/adapters';
import {loadCharacterLibrary} from '@/lib/arena/character-store';
import {cardImageUrl} from '@/lib/arena/character-registry';
export default function Game(){
 const [view,setView]=useState('control'),[sport,setSport]=useState<Sport>('cornhole'),[user,setUser]=useState('user-doug'),[opponent,setOpponent]=useState('user-dan'),[ownCard,setOwnCard]=useState('card-dan'),[oppCard,setOppCard]=useState('card-doug'),[strategy,setStrategy]=useState<Strategy>('steady'),[mode,setMode]=useState('exhibition'),[tie,setTie]=useState('draw'),[secret,setSecret]=useState(false),[showcase,setShowcase]=useState(false),[setupOpen,setSetupOpen]=useState(false),[panel,setPanel]=useState<string|null>(null),[state,setState]=useState<SavedState|null>(null),[rec,setRec]=useState<Recording|null>(null),[time,setTime]=useState(0),[paused,setPaused]=useState(false),[speed,setSpeed]=useState(1),[sound,setSound]=useState(false),[reduced,setReduced]=useState(false),[low,setLow]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[profile,setProfile]=useState<string|null>(null),[previewCard,setPreviewCard]=useState('card-dan'),[previewClip,setPreviewClip]=useState<Clip>('idle'),[importText,setImportText]=useState(''),[importStatus,setImportStatus]=useState(''),[draftPolicy,setDraftPolicy]=useState<Policy>({...DEFAULT_POLICY}),[metrics,setMetrics]=useState<any>(null),[clean,setClean]=useState(false);
 const services=useRef<ArenaServices|null>(null);
 const clock=useRef<PlaybackClock|null>(null);if(!clock.current)clock.current=new PlaybackClock();const audio=useRef<ArenaAudio|null>(null);if(!audio.current)audio.current=new ArenaAudio();const repository=useRef<LocalArenaRepository|null>(null),pendingAuto=useRef(false),setupExiting=useRef(false),arenaReady=useRef(false),startGuard=useRef(false),lastCue=useRef(''),lastSave=useRef(0),recRef=useRef(rec);recRef.current=rec;
 useEffect(()=>{services.current=createDemoServices(localStorage);repository.current=services.current.results as LocalArenaRepository;let mounted=true;loadCharacterLibrary().then(()=>{if(!mounted)return;const s=repository.current!.load();setState(s);setDraftPolicy({...s.policy});}).catch(e=>{if(mounted)setError('Character library: '+String(e));});setReduced(matchMedia('(prefers-reduced-motion: reduce)').matches);let prior=0;const unsub=clock.current!.subscribe(t=>{if(Math.abs(t-prior)>.045||t>=clock.current!.duration){setTime(t);prior=t;}const r=recRef.current;if(r&&Math.abs(t-lastSave.current)>2){lastSave.current=t;try{repository.current?.savePlayback(r.id,t);}catch{setError('Playback could not be saved. Keep this tab open and export your recording.');}}});const hide=()=>{if(recRef.current)repository.current?.savePlayback(recRef.current.id,clock.current!.time);};addEventListener('pagehide',hide);const onStorage=()=>{loadCharacterLibrary().then(()=>{if(mounted)setState(repository.current!.load());}).catch(()=>{});};addEventListener('storage',onStorage);return()=>{mounted=false;unsub();clock.current!.stop();audio.current!.destroy();removeEventListener('pagehide',hide);removeEventListener('storage',onStorage);};},[]);
 const status=rec?revealed(rec,time):null,complete=!!status?.complete,hiddenId=rec?(complete?null:rec.id):state?.active?.id,displayState=state&&hiddenId?{...state,ledger:state.ledger.filter(a=>a.contestId!==hiddenId),recordings:state.recordings.filter(r=>r.id!==hiddenId)}:state,table=displayState?standings(displayState):[],myRow=table.find(r=>r.user.id===user),entry=state?availableEntry(state,user,sport):undefined,playing=!!rec&&!complete;
 const selectedCards:[string,string]=rec?[rec.setup.participants[0].cardId,rec.setup.participants[1].cardId]:[ownCard,oppCard];
 const arenaCue=useCallback((cue:import('@/lib/arena/engine/core/BattlePlan').DirectorCue)=>{audio.current?.event(cue);},[]);
 const tryAutoPlay=useCallback(()=>{if(pendingAuto.current&&arenaReady.current&&!setupExiting.current){pendingAuto.current=false;clock.current!.paused=false;setPaused(false);}},[]);
 const setupClosed=useCallback(()=>{setupExiting.current=false;tryAutoPlay();},[tryAutoPlay]);
 const stageReady=useCallback(()=>{arenaReady.current=true;setReady(true);tryAutoPlay();},[tryAutoPlay]),stageError=useCallback((e:string)=>setError(e),[]),metricsReady=useCallback((m:any)=>setMetrics(m),[]);
 const backToLobby=()=>{audio.current!.stop();if(rec)repository.current?.savePlayback(rec.id,time);setRec(null);setTime(0);clock.current!.start(0,Infinity);setPaused(false);setState(repository.current!.load());setView('play');};
 const replay=(r:Recording,resume=0)=>{audio.current!.stop();lastCue.current='';setPanel(null);setView('play');setSport(r.setup.sport);setRec(r);setTime(resume);arenaReady.current=r.id===rec?.id;setReady(arenaReady.current);pendingAuto.current=r.id!==rec?.id&&resume===0;clock.current!.start(resume,r.duration);clock.current!.paused=r.id!==rec?.id||resume!==0;setPaused(clock.current!.paused);setSpeed(1);clock.current!.speed=1;};
 const start=async()=>{if(startGuard.current||!repository.current)return;startGuard.current=true;setBusy(true);setError('');try{const ranked=mode==='ranked';if(ranked&&!entry)throw Error('No counted entry remains for this event. Choose Exhibition.');const users=ranked?entry!.users:[user,opponent];await services.current!.identity.select(user);const owned=(await Promise.all(users.map(uid=>services.current!.ownership.list(uid)))).flat();const participants=users.map(uid=>{const isMe=uid===user;const cardId=isMe?ownCard:(ranked?'card-doug':oppCard);const copy=owned.find(c=>c.userId===uid&&c.cardId===cardId);if(!copy)throw Error('No owned copy is available for this competitor.');return{userId:uid,copyId:copy.id,cardId,strategy:isMe?strategy:'steady' as Strategy};}) as Setup['participants'];const setup:Setup={id:ranked?'contest-'+entry!.id:crypto.randomUUID(),seed:ranked?entry!.seed:showcase&&sport==='cornhole'?'velvet-paw-29':crypto.randomUUID(),sport,participants,characterAssets:participants.map(p=>state!.imports.find(a=>a.cardId===p.cardId)??manifest(p.cardId,cardById(p.cardId).asset,cardById(p.cardId).family)) as Setup['characterAssets'],mode:ranked?'ranked':'exhibition',tie:tie==='paired'?'paired':'draw',secret:ranked?false:secret,showcase:!ranked&&showcase&&sport==='cornhole',entryId:ranked?entry!.id:undefined,policy:{...state!.policy},rulesVersion:RULES_VERSION,createdAt:new Date().toISOString()};const result=await repository.current.commit(setup);setState(result.state);setupExiting.current=true;setSetupOpen(false);replay(result.recording);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);startGuard.current=false;}};
 const pause=()=>{clock.current!.paused=!clock.current!.paused;setPaused(clock.current!.paused);if(clock.current!.paused)audio.current!.stop();};
 const skip=()=>{if(!rec)return;audio.current!.stop();clock.current!.seek(rec.duration);setTime(rec.duration);repository.current?.savePlayback(rec.id,rec.duration);setState(repository.current!.load());};
 const navigate=(to:string)=>{if(playing){clock.current!.paused=true;setPaused(true);audio.current!.stop();}setView(to);};
 const exportData=(data:unknown,name:string)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
 const webState=useRef<any>(null);webState.current={sport,score:status?.scores??[0,0],complete,rec,table};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'read_arena',description:'Read the current revealed score and leaderboard.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const p=webState.current;return{event:p.sport,score:p.score,complete:p.complete,leaderboard:p.table.map((r:any)=>({user:r.user.name,points:r.points,rank:r.rank}))};}},{name:'configure_arena_event',description:'Select a lobby event. Does not start or award a contest.',inputSchema:{type:'object',properties:{event:{type:'string',enum:SPORTS}},required:['event'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!SPORTS.includes(input?.event))throw Error('Choose a supported event.');if(webState.current.rec)throw Error('Return to the lobby before configuring a contest.');setSport(input.event);setView('play');return{selectedEvent:input.event};}}];for(const tool of tools)Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 const common={sport,setSport,mode,setMode,user,setUser,opponent,setOpponent,ownCard,setOwnCard,oppCard,setOppCard,strategy,setStrategy,tie,setTie,secret,setSecret,showcase,setShowcase,entry,state,setState,busy,error,start};
 const panelProps={panel,setPanel,state:displayState,setState,sport,user,rec,status,table,profile,replay,exportData,reduced,setReduced,low,setLow,draftPolicy,setDraftPolicy,metrics,repository,clock,audio,setRec,setError,previewCard,importText,setImportText,importStatus,setImportStatus};

 return <main className={'club-shell '+(clean?'spectator-clean':'')+(complete?' completed':'')}>
 <header className="club-header"><a className="brand" href="/" onClick={e=>{e.preventDefault();backToLobby();}}><span>WILL YOU BE MY HERO?</span><strong>ARENA<i>★</i></strong></a><nav aria-label="Main"><button className={view==='control'?'active':''} onClick={()=>navigate('control')}>Play</button><button className={view==='play'?'active':''} onClick={()=>navigate('play')}>Watch</button><button className={view==='standings'?'active':''} onClick={()=>navigate('standings')}>Standings</button><button className={view==='collection'?'active':''} onClick={()=>navigate('collection')}>The collection</button></nav><div className="header-tools"><span className="local-label">LOCAL DEMO</span><button className="icon-button" aria-label="Arena settings" onClick={()=>setPanel('settings')}><Settings2 size={20}/></button></div></header>
 {view==='play'&&<>
 <section className="lobby-title"><div><p className="eyebrow">BACKYARD SPORTS / {String(SPORTS.indexOf(sport)+1).padStart(2,'0')}</p><h1>{EVENTS[sport].name}<span className="title-slash">/</span><em>{rec?(complete?'FINAL':'LIVE'):'HEAD TO HEAD'}</em></h1></div><button className="standing-chip" onClick={()=>{setProfile(user);setPanel('user');}}><Trophy size={22}/><div><strong>{myRow?.points??0}<small> CLUB POINTS</small></strong><span>{userById(user).name} · Rank {myRow?.rank??'—'} · {state?Math.max(0,state.policy.allowance-rankedPlayed(state,user)):'—'} entries left</span></div><ChevronRight size={16}/></button></section>
 {!rec&&state?.active&&<div className="resume-banner"><span>Saved at {Math.floor(state.active.time)} seconds. Your result is waiting.</span><Button variant="outline" onClick={()=>{const r=state.recordings.find(r=>r.id===state.active!.id);if(r)replay(r,state.active!.time);}}>Resume contest <Play size={14}/></Button></div>}
 {!rec&&<div className="event-dock"><span className="dock-label">CHOOSE YOUR EVENT</span><div className="event-buttons">{SPORTS.map((e,i)=><button aria-pressed={sport===e} className={sport===e?'selected':''} key={e} onClick={()=>setSport(e)}><span>0{i+1}</span>{EVENTS[e].name}</button>)}</div></div>}
 <div className={'arena-layout '+(rec?'live-layout':'')}>
 <div className="stage-column"><section className={'club-stage '+(rec?'in-contest':'')} aria-label="The backyard arena"><ArenaStage onCue={arenaCue} sport={sport} recording={rec} clock={clock.current} cards={selectedCards} reduced={reduced} low={low} onReady={stageReady} onError={stageError} onMetrics={metricsReady} imported={state?.imports}/>
 <div className="stage-top"><span>WYBMH / COURT 01</span><div className="stage-controls"><button aria-label={sound?'Mute sound':'Enable sound'} onClick={async()=>setSound(await audio.current!.toggle())}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button aria-label="Clean spectator view" onClick={()=>setClean(!clean)}><Maximize2 size={18}/></button></div></div>
 {rec?<div className="scoreboard" aria-label="Live score">{rec.setup.participants.map((p,i)=><div key={i} className={status?.current?.actor===i?'actor':''}><span>{cardById(p.cardId).name.split(' ')[0]}</span><strong>{status?.scores[i]??0}</strong><small>{status?.resolved.filter(a=>a.actor===i).length??0}/{rec.attempts.filter(a=>a.actor===i).length} {EVENTS[sport].unit}</small></div>)}<span className="scoreboard-event">{EVENTS[sport].name}<small>{rec.setup.mode==='ranked'?'COUNTED ENTRY':'EXHIBITION / NO POINTS'}</small></span></div>:<div className="stage-event-label"><span>THE SAME CREW.</span><h2>HIGHER STAKES.</h2><p>{EVENTS[sport].attempts} {EVENTS[sport].unit} each / Fully automatic</p></div>}
 <div className="stage-bottom"><span>{rec?time<rec.introDuration?'CARDS TO COURT':complete?'FINAL SCORE':`ROUND ${(status?.current?.round??0)+1}`:'PEPPERONI CHEESERS'}</span><span>{rec?status?.current?.special?'HEAT CHECK / COSMETIC':paused?'PAUSED':complete?'FULL TIME':'● LIVE':'HOME COURT ADVANTAGE: NONE'}</span></div></section>
 {error&&<div className="error-box" role="alert">{error}<button onClick={()=>{setError('');if(rec)replay(rec,time);else setLow(!low);}}>Restore arena</button></div>}
 {rec&&<div className="playback-progress" role="progressbar" aria-valuenow={Math.round(time/rec.duration*100)} aria-valuemin={0} aria-valuemax={100} aria-label="Contest playback"><span style={{width:Math.min(100,time/rec.duration*100)+'%'}}/></div>}
 <div className="floor-caption"><span>{rec?`COLLECTIONS: ${rec.setup.participants.map(p=>userById(p.userId).name).join(' / ')} / ${rec.setup.mode}`:'GROSS POINTS. EQUAL ATTEMPTS. SETTLE IT ON THE COURT.'}</span><button onClick={()=>setPanel('rules')}>House rules <Info size={14}/></button></div>
 </div>
 <aside className="competitor-station"><div className="station-heading"><span>{rec?'THE MATCH CARD':'ON THE CARD'}</span><span>02 PLAYERS</span></div><div className="duel-cards">{selectedCards.map((id,i)=>{const c=cardById(id);return <div key={i}><button disabled={!!rec} onClick={()=>setSetupOpen(true)} aria-label={'Change competitor '+(i+1)}><img src={cardImageUrl(c.id)} alt={c.name+' original collectible card'}/></button><strong>{c.name.split(' ')[0]}</strong><small>{i===0?'THROWS FIRST':'THROWS SECOND'}</small></div>})}<span className="duel-vs">VS</span></div>
 {rec?<div className="watch-desk"><p className="live-copy" aria-live="polite" aria-atomic="true">{matchNarration(rec,time)}</p><div className="playback-controls"><button className="icon-button" aria-label={paused?'Resume playback':'Pause playback'} onClick={pause}>{paused?<Play size={19}/>:<Pause size={19}/>}</button><button className="speed-button" onClick={()=>{const next=speed===1?2:speed===2?.5:1;setSpeed(next);clock.current!.speed=next;}} aria-label="Playback speed">{speed}×</button><button className="icon-button" aria-label="Skip to result" onClick={skip}><SkipForward size={19}/></button><button className="icon-button" aria-label="Attempt history" onClick={()=>setPanel('attempts')}><History size={19}/></button></div>{time<rec.introDuration&&<button className="text-button" onClick={()=>{clock.current!.seek(rec.introDuration);setTime(rec.introDuration);}}>Skip entrances <ArrowUpRight size={15}/></button>}<p className="station-note">{rec.setup.mode==='ranked'?'Points post once. Replay as often as you like.':'EXHIBITION / NO LEADERBOARD POINTS'}</p></div>:<><p className="station-note">Choose your matchup. Every throw plays out automatically.</p><Button className="primary-cta" disabled={!state} onClick={()=>setSetupOpen(true)}>Set up showdown <ArrowUpRight size={22}/></Button><span className="entry-stamp">{EVENTS[sport].attempts} {EVENTS[sport].unit.toUpperCase()} EACH / ~{Math.round(matchEstimate(sport))} SEC</span></>}
 </aside></div>
 {complete&&rec&&<section className="result-panel"><div><p className="eyebrow">{rec.setup.mode==='ranked'?'COUNTED RESULT / POINTS POSTED':'EXHIBITION / NO LEADERBOARD POINTS'}</p><h2>{rec.winner===null?'HONORS SHARED.':cardById(rec.setup.participants[rec.winner].cardId).name.split(' ')[0]+' WINS.'}</h2><p>{rec.scores[0]} — {rec.scores[1]} <span>{EVENTS[sport].name}{rec.unresolvedDraw?' / Unresolved draw after three extra pairs':''}</span></p></div><div className="result-awards">{rec.setup.participants.map(p=>{const row=table.find(r=>r.user.id===p.userId),award=awardsFor(rec).find(a=>a.userId===p.userId);const before=state?standings({...state,ledger:state.ledger.filter(a=>a.contestId!==rec.id)}).find(r=>r.user.id===p.userId):null;return <div key={p.userId}><span>{userById(p.userId).name}</span><strong>+{award?.delta??0}<small> PTS</small></strong><span>{row?.points??0} total / Rank {row?.rank??'—'}{award&&before&&before.rank!==row?.rank?' (was '+before.rank+')':''}</span></div>})}</div><div className="result-actions"><Button className="primary-cta" onClick={backToLobby}>Next showdown <ArrowUpRight size={19}/></Button><button onClick={()=>replay(rec)}><RotateCcw size={16}/> Replay same recording</button></div></section>}
 </>}
 {view==='control'&&<PlayableArena imports={state?.imports??[]} reduced={reduced}/>}
 {view!=='play'&&view!=='control'&&<SecondaryViews {...{view,state:displayState,filter,setFilter,user,setProfile,setPanel,previewCard,setPreviewCard,previewClip,setPreviewClip,clock,sport,reduced,low,stageReady,stageError,setImportText,onCharacterInstalled:(id:string)=>{setState(repository.current!.load());setPreviewCard(id);setPreviewClip('idle');setOwnCard(id);setShowcase(false);}}}/>}
 <footer><span>WILL YOU BE MY HERO? <b>ARENA</b></span><div><button onClick={()=>setPanel('rules')}>House rules</button><button onClick={()=>setPanel('history')}>History</button><span>Sound {sound?'on':'off'}</span></div></footer>
 <SetupDialog {...common} open={setupOpen} setOpen={setSetupOpen} onClosed={setupClosed}/><Panels {...panelProps}/></main>;
}
