'use client';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Play,Download} from 'lucide-react';
import {useState} from 'react';
import {CARDS,EVENTS,cardById,findCard,userById,type Recording} from '@/lib/arena/model';
import {MAX_ALLOWANCE} from '@/lib/arena/persistence';
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
const signed=(n:number)=>(n<0?'−':'+')+Math.abs(n);
const modeName=(mode:string)=>mode==='ranked'?'Counted entry':'Exhibition';
const cardNames=(r:Recording)=>r.setup.participants.map(q=>findCard(q.cardId)?.name??'Unknown card').join(' vs ');
const missingCard=(r:Recording)=>r.setup.participants.some(q=>!findCard(q.cardId));
import {manifest,validateAsset} from '@/lib/arena/assets';
import {registeredManifest,resolveCharacterImage} from '@/lib/arena/character-registry';
export default function Panels(p:any){const {panel,setPanel,state,sport,user,rec,status,table,profile,replay,exportData,draftPolicy,setDraftPolicy}=p;const event=EVENTS[sport as keyof typeof EVENTS];const [feedback,setFeedback]=useState({panel:null as string|null,settings:'',reset:'',importOk:false}),[importBusy,setImportBusy]=useState(false);const shown=feedback.panel===panel?feedback:{panel,settings:'',reset:'',importOk:false},settingsError=shown.settings,resetError=shown.reset,importOk=shown.importOk;const setSettingsError=(settings:string)=>setFeedback({...shown,settings}),setResetError=(reset:string)=>setFeedback({...shown,reset}),setImportOk=(ok:boolean)=>setFeedback({...shown,importOk:ok});return <Dialog open={panel!==null} onOpenChange={v=>{if(!v){setPanel(null);setFeedback({panel:null,settings:'',reset:'',importOk:false});}}}><DialogContent className={'info-dialog '+(panel==='import'?'wide':'')}><DialogHeader><DialogTitle>{({rules:'House rules',settings:'Arena settings',history:'Your contest history',attempts:'The contest, as it happened',user:'Club member record',import:'Card → competitor mapping',reset:'Reset the local demo?'} as any)[panel??'']}</DialogTitle><DialogDescription>{panel==='import'?'A card image and an animated competitor are two connected assets.':panel==='settings'?'Prototype defaults. Changes apply to future entries.':'Will You Be My Hero? — Arena / local demo'}</DialogDescription></DialogHeader>
 {panel==='rules'&&<div className="prose">{p.view==='control'&&<p className="quiet-note">These are the Watch rules. Play practice never awards points.</p>}<p>Choose a sport and competing cards, review the setup, and press <strong>Start showdown</strong>. The entire contest is automatic. Viewing controls never change the result.</p><h3>{event.name}</h3><ul>{event.rules.map(r=><li key={r}>{r}</li>)}</ul><p>Default ties are draws. With <strong>Up to 3 extra equal pairs</strong>, a tie is followed by at most three extra pairs of attempts; both players always receive an attempt. A remaining tie is recorded as a draw.</p><h3>Club points</h3>{state&&!state.policy.rankedEnabled?<p>Counted entries are switched off, so no contest earns points. Exhibitions are unlimited.</p>:<p>Win {state?.policy.win??3}, draw {state?.policy.draw??1}, loss {state?.policy.loss??0}. Sports scores stay separate. Each user has an equal {Math.min(state?.policy.allowance??4,MAX_ALLOWANCE)}-entry allowance. Scheduled opponent, order, and seed lock before <strong>Start showdown</strong>. Exhibition is unlimited and earns no points.</p>}<p>Heat check is a cosmetic round label on round three, for exhibitions only. It never adds points, and rarity gives no power bonus.</p><p className="quiet-note">Proposed arcade rules, not official league rules.{state&&` Scoring policy: ${state.policy.id}.`}</p></div>}
 {panel==='settings'&&<div className="settings-form"><label className="check-row"><Checkbox checked={p.reduced} onCheckedChange={v=>p.setReduced(!!v)}/>Reduced motion</label><label className="check-row"><Checkbox checked={p.low} onCheckedChange={v=>p.setLow(!!v)}/>Lower graphics quality</label><hr/><h3>Host · prototype scoring</h3><div className="policy-fields">{(['win','draw','loss','allowance'] as const).map(k=><label key={k}>{k==='allowance'?'Entries / user':k}<input type="number" min="0" max={k==='allowance'?MAX_ALLOWANCE:100} aria-invalid={!!settingsError||undefined} value={draftPolicy[k]} onChange={e=>setDraftPolicy({...draftPolicy,[k]:Number(e.target.value)})}/></label>)}</div><label className="check-row"><Checkbox checked={draftPolicy.rankedEnabled} onCheckedChange={v=>setDraftPolicy({...draftPolicy,rankedEnabled:!!v})}/>Counted entries enabled</label><p className="quiet-note">Ownership, scheduled opponents, and supported assets are required. Historical points retain their saved policy. Existing playback stays unchanged.</p>{settingsError&&<p role="alert" className="inline-error">{settingsError}</p>}<Button className="primary-cta" onClick={async()=>{setSettingsError('');try{const s=await p.repository.current.updatePolicy(draftPolicy);p.setState(s);p.setSaveError('');setDraftPolicy(s.policy);setPanel(null);}catch(e){setSettingsError(message(e));}}}>Save for future entries</Button><div className="settings-links"><button onClick={()=>p.exportSave('clubhouse-save.json')}><Download size={15}/>Export local save</button><button onClick={()=>setPanel('reset')}>Reset demo…</button></div>{p.metrics&&<details><summary>Performance snapshot</summary><p>{p.metrics.fps} fps · {p.metrics.frameMs} ms mean frame interval</p><p>{p.metrics.drawCalls} draw calls · {p.metrics.loadMs} ms arena asset load</p><p className="quiet-note">Graphics memory estimate: {p.metrics.textureMB} MB. Frame interval measured in this browser.</p></details>}</div>}
 {panel==='reset'&&<div className="prose"><p>This restores sample contests and removes locally played contests, awards, and imported mappings from this browser. Export your save first to keep them.</p><Button variant="outline" onClick={()=>p.exportSave('clubhouse-before-reset.json')}>Export save</Button><Button className="reset-button" onClick={async()=>{setResetError('');try{const s=await p.repository.current.reset();p.clock.current.stop();p.audio.current.stop();p.setState(s);p.setSaveError('');p.setRec(null);setPanel(null);setDraftPolicy(s.policy);p.clock.current.start(0,Infinity);}catch(e){setResetError(message(e));}}}>Reset demo data</Button>{resetError&&<p role="alert" className="inline-error">The demo could not be reset: {resetError}</p>}</div>}
 {panel==='history'&&<div className="history-list">{!state?<p>The Arena save could not be read.</p>:<>{state.recordings.filter((r:any)=>r.setup.participants.some((p:any)=>p.userId===user)).slice().reverse().map((r:any)=>{const missing=missingCard(r);return <button key={r.id} disabled={missing} onClick={()=>replay(r)}><span><strong>{EVENTS[r.setup.sport as keyof typeof EVENTS].name}</strong><small>{cardNames(r)} · {modeName(r.setup.mode)}</small></span><span>{r.scores.join(' — ')}<small>{signed(state.ledger.find((a:any)=>a.contestId===r.id&&a.userId===user)?.delta??0)} points · {missing?'This recording uses a character that is no longer installed.':'Replay'}</small></span><Play size={16}/></button>;})}{!state.recordings.some((r:any)=>r.setup.participants.some((p:any)=>p.userId===user))&&<p>No contests yet. Your first result will appear here.</p>}</>}</div>}
 {panel==='attempts'&&rec&&<div className="history-list">{status?.contacts.map((a:any)=><div key={a.id}><span><strong>{a.index+1}. {findCard(rec.setup.participants[a.actor].cardId)?.name??'Unknown card'}</strong><small>{a.contact.replace('-',' ')} · {a.commentary}</small></span><strong>{signed(a.score)}</strong></div>)}{!status?.contacts.length&&<p>The first attempt has not landed yet.</p>}<button className="text-button" onClick={()=>exportData(rec,'arena-'+rec.id+'.json')}><Download size={16}/>Export immutable recording</button></div>}
 {panel==='user'&&profile&&<div className="user-record"><h2>{userById(profile).name}</h2>{(()=>{const r=table.find((r:any)=>r.user.id===profile);return <div className="record-numbers"><div><strong>{r?.points??0}</strong>points</div><div><strong>{r?.wins??0}</strong>wins</div><div><strong>{r?.draws??0}</strong>draws</div><div><strong>{r?.losses??0}</strong>losses</div></div>})()}<div className="history-list">{state?.recordings.filter((r:any)=>r.setup.participants.some((p:any)=>p.userId===profile)).map((r:any)=>{const missing=missingCard(r);return <button key={r.id} disabled={missing} onClick={()=>replay(r)}><span>{EVENTS[r.setup.sport as keyof typeof EVENTS].name}<small>{modeName(r.setup.mode)}{missing&&' · This recording uses a character that is no longer installed.'}</small></span><strong>{r.scores.join(' — ')}</strong><Play size={15}/></button>;})}</div></div>}
 {panel==='import'&&<div className="import-panel"><p>Prepare transparent illustrated poses, align the feet, and map each hand position. Attach the finished cutout sequence here. Original card art stays separate.</p><label htmlFor="manifest-json">Asset manifest JSON</label><textarea id="manifest-json" value={p.importText} onChange={e=>p.setImportText(e.target.value)} spellCheck={false}/><div className="import-buttons"><Button variant="outline" onClick={()=>exportData(registeredManifest(p.previewCard)??manifest(p.previewCard,cardById(p.previewCard).asset,cardById(p.previewCard).family),'character-manifest.json')}>Download example</Button><Button className="primary-cta" disabled={importBusy} onClick={async()=>{setImportBusy(true);setImportOk(false);try{let input:unknown;try{input=JSON.parse(p.importText);}catch(e){p.setImportStatus('Invalid JSON: '+message(e));return;}const result=validateAsset(input);if(result.errors.length){p.setImportStatus(result.errors.join('\n'));return;}const a=result.asset!;if(!CARDS.some(c=>c.id===a.cardId)){p.setImportStatus('Add this stable cardId to the CardCatalog adapter before attaching its animation.');return;}if(a.parts!==undefined&&(typeof a.parts!=='object'||a.parts===null||Array.isArray(a.parts))){p.setImportStatus('parts must be an object of named part images.');return;}const urls=[a.cardImage,a.sheet,...Object.values(a.frames??{}).map(f=>f.url),...Object.values(a.parts??{}).map(q=>q?.url)].filter((url):url is string=>typeof url==='string');const failed=(await Promise.all(urls.map(async url=>new Promise<string|null>(resolve=>{const image=new Image();image.onload=()=>resolve(null);image.onerror=()=>resolve(url);image.src=resolveCharacterImage(url);})))).filter(Boolean);if(failed.length){p.setImportStatus('Could not load assets:\n'+failed.join('\n'));return;}let s;try{s=await p.repository.current.saveAssets(a);}catch(e){p.setImportStatus('The mapping could not be saved: '+message(e));return;}p.setState(s);p.setSaveError('');setImportOk(true);p.setImportStatus('Mapping saved. Open the motion preview to review every supported action.');}finally{setImportBusy(false);}}}>{importBusy?'Checking the images…':'Validate & attach'}</Button></div><pre aria-live="polite" className={importOk?'import-ok':undefined}>{p.importStatus}</pre><p className="quiet-note">Imported mappings remain local. View-angle, animation-state, attachment, and asset checks run before saving.</p></div>}
 </DialogContent></Dialog>}


