'use client';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Play,Download} from 'lucide-react';
import {CARDS,EVENTS,cardById,userById} from '@/lib/arena/model';
import {manifest,validateAsset} from '@/lib/arena/assets';
export default function Panels(p:any){const {panel,setPanel,state,sport,user,rec,status,table,profile,replay,exportData,draftPolicy,setDraftPolicy}=p;const event=EVENTS[sport as keyof typeof EVENTS];return <Dialog open={panel!==null} onOpenChange={v=>!v&&setPanel(null)}><DialogContent className={'info-dialog '+(panel==='import'?'wide':'')}><DialogHeader><DialogTitle>{({rules:'Clubhouse rules',settings:'Make yourself at home',history:'Your contest history',attempts:'The contest, as it happened',user:'Club member record',import:'Card → competitor mapping',reset:'Reset the local demo?'} as any)[panel??'']}</DialogTitle><DialogDescription>{panel==='import'?'A card image and an animated competitor are two connected assets.':panel==='settings'?'Prototype defaults. Changes apply to future entries.':'Will You Be My Hero? — Arena · local demo'}</DialogDescription></DialogHeader>
 {panel==='rules'&&<div className="prose"><p>Choose a sport and competing cards, review the setup, and press Start. The entire contest is automatic. Viewing controls never change the result.</p><h3>{event.name}</h3><ul>{event.rules.map(r=><li key={r}>{r}</li>)}</ul><p>Default ties are draws. Optional sudden death allows at most three extra pairs; both players always receive an attempt. A remaining tie is recorded as a draw.</p><h3>Club points</h3><p>Win {state?.policy.win??3}, draw {state?.policy.draw??1}, loss {state?.policy.loss??0}. Sports scores stay separate. Each user has an equal {state?.policy.allowance??4}-entry allowance. Scheduled opponent, order, and seed lock before Start. Exhibition is unlimited and earns no points.</p><p>Blacklight Bloom is a preselected cosmetic effect on round three. It never adds points. Prototype ranked entries exclude Secret effects; rarity gives no power bonus.</p><p className="quiet-note">Proposed arcade rules, not official league rules. Scoring policy: {state?.policy.id}.</p></div>}
 {panel==='settings'&&<div className="settings-form"><label className="check-row"><Checkbox checked={p.reduced} onCheckedChange={v=>p.setReduced(!!v)}/>Reduced motion</label><label className="check-row"><Checkbox checked={p.low} onCheckedChange={v=>p.setLow(!!v)}/>Lower graphics quality</label><hr/><h3>Host · prototype scoring</h3><div className="policy-fields">{(['win','draw','loss','allowance'] as const).map(k=><label key={k}>{k==='allowance'?'Entries / user':k}<input type="number" min="0" max="100" value={draftPolicy[k]} onChange={e=>setDraftPolicy({...draftPolicy,[k]:Number(e.target.value)})}/></label>)}</div><label className="check-row"><Checkbox checked={draftPolicy.rankedEnabled} onCheckedChange={v=>setDraftPolicy({...draftPolicy,rankedEnabled:!!v})}/>Counted entries enabled</label><p className="quiet-note">Ownership, scheduled opponents, and supported assets are required. Historical points retain their saved policy. Existing playback stays unchanged.</p><Button className="primary-cta" onClick={async()=>{try{const s=await p.repository.current.updatePolicy(draftPolicy);p.setState(s);setDraftPolicy(s.policy);setPanel(null);}catch(e){p.setError(String(e));}}}>Save for future entries</Button><div className="settings-links"><button onClick={()=>exportData(state,'clubhouse-save.json')}><Download size={15}/>Export local save</button><button onClick={()=>setPanel('reset')}>Reset demo…</button></div>{p.metrics&&<details><summary>Performance snapshot</summary><p>{p.metrics.fps} fps · {p.metrics.frameMs} ms mean frame interval</p><p>{p.metrics.drawCalls} draw calls · {p.metrics.loadMs} ms arena asset load</p><p className="quiet-note">Graphics memory estimate: {p.metrics.textureMB} MB. Frame interval measured in this browser.</p></details>}</div>}
 {panel==='reset'&&<div className="prose"><p>This restores sample contests and removes locally played contests, awards, and imported mappings from this browser. Export your save first to keep them.</p><Button variant="outline" onClick={()=>exportData(state,'clubhouse-before-reset.json')}>Export save</Button><Button className="reset-button" onClick={async()=>{p.clock.current.stop();p.audio.current.stop();const s=await p.repository.current.reset();p.setState(s);p.setRec(null);setPanel(null);setDraftPolicy(s.policy);p.clock.current.start(0,Infinity);}}>Reset demo data</Button></div>}
 {panel==='history'&&<div className="history-list">{state?.recordings.filter((r:any)=>r.setup.participants.some((p:any)=>p.userId===user)).slice().reverse().map((r:any)=><button key={r.id} onClick={()=>replay(r)}><span><strong>{EVENTS[r.setup.sport as keyof typeof EVENTS].name}</strong><small>{r.setup.participants.map((p:any)=>cardById(p.cardId).name).join(' vs ')} · {r.setup.mode}</small></span><span>{r.scores.join(' — ')}<small>+{state.ledger.find((a:any)=>a.contestId===r.id&&a.userId===user)?.delta??0} points · Replay</small></span><Play size={16}/></button>)}{!state?.recordings.some((r:any)=>r.setup.participants.some((p:any)=>p.userId===user))&&<p>No contests yet. Your first result will appear here.</p>}</div>}
 {panel==='attempts'&&rec&&<div className="history-list">{status?.contacts.map((a:any)=><div key={a.id}><span><strong>{a.index+1}. {cardById(rec.setup.participants[a.actor].cardId).name}</strong><small>{a.contact.replace('-',' ')} · {a.commentary}</small></span><strong>+{a.score}</strong></div>)}{!status?.contacts.length&&<p>The first attempt has not landed yet.</p>}<button className="text-button" onClick={()=>exportData(rec,'arena-'+rec.id+'.json')}><Download size={16}/>Export immutable recording</button></div>}
 {panel==='user'&&profile&&<div className="user-record"><h2>{userById(profile).name}</h2>{(()=>{const r=table.find((r:any)=>r.user.id===profile);return <div className="record-numbers"><div><strong>{r?.points??0}</strong>points</div><div><strong>{r?.wins??0}</strong>wins</div><div><strong>{r?.draws??0}</strong>draws</div><div><strong>{r?.losses??0}</strong>losses</div></div>})()}<div className="history-list">{state?.recordings.filter((r:any)=>r.setup.participants.some((p:any)=>p.userId===profile)).map((r:any)=><button key={r.id} onClick={()=>replay(r)}><span>{EVENTS[r.setup.sport as keyof typeof EVENTS].name}<small>{r.setup.mode}</small></span><strong>{r.scores.join(' — ')}</strong><Play size={15}/></button>)}</div></div>}
 {panel==='import'&&<div className="import-panel"><p>Prepare transparent body layers, align the ground anchor, rig the joints, and author the sport poses. Map the finished assets here. A single card upload is not a finished competitor.</p><label htmlFor="manifest-json">Asset manifest JSON</label><textarea id="manifest-json" value={p.importText} onChange={e=>p.setImportText(e.target.value)} spellCheck={false}/><div className="import-buttons"><Button variant="outline" onClick={()=>exportData(manifest(p.previewCard,cardById(p.previewCard).asset,cardById(p.previewCard).family),'character-manifest.json')}>Download example</Button><Button className="primary-cta" onClick={async()=>{try{const result=validateAsset(JSON.parse(p.importText));if(result.errors.length){p.setImportStatus(result.errors.join('\n'));return;}const a=result.asset!;if(!CARDS.some(c=>c.id===a.cardId)){p.setImportStatus('Add this stable cardId to the CardCatalog adapter before attaching its animation.');return;}const urls=[a.cardImage,a.sheet,...Object.values(a.parts).map(p=>p.url)];const failed=(await Promise.all(urls.map(async url=>new Promise<string|null>(resolve=>{const image=new Image();image.onload=()=>resolve(null);image.onerror=()=>resolve(url);image.src=url;})))).filter(Boolean);if(failed.length){p.setImportStatus('Could not load assets:\n'+failed.join('\n'));return;}const s=await p.repository.current.saveAssets(a);p.setState(s);p.setImportStatus('Mapping saved. Open the motion preview to review every supported action.');}catch(e){p.setImportStatus('Invalid JSON: '+String(e));}}}>Validate & attach</Button></div><pre role="status">{p.importStatus}</pre><p className="quiet-note">Imported mappings remain local. View-angle, animation-state, attachment, and asset checks run before saving.</p></div>}
 </DialogContent></Dialog>}


