import {USERS,COPIES,SCHEDULE,CARDS,DEFAULT_POLICY,type SavedState,type Recording,type Award,type Policy,type Sport,type Setup,type AssetManifest,type Entry} from './model';
import {hash,simulate,validateRecording,RULES_VERSION} from './simulation';
import {completionTime} from './match-timeline';
export const STORAGE_KEY='wybmh-paper-arena-v2';
export const LEADERBOARD_ID='paper-arena-demo';
export interface ArenaRepository {load():SavedState;commit(setup:Setup):Promise<{recording:Recording;state:SavedState;existing:boolean}>;savePlayback(id:string,time:number):void;updatePolicy(policy:Policy):Promise<SavedState>;saveAssets(asset:AssetManifest):Promise<SavedState>;reset():Promise<SavedState>}
export function awardsFor(rec:Recording):Award[]{if(rec.setup.mode!=='ranked')return[];return rec.setup.participants.map((p,i)=>{const outcome=rec.winner===null?'draw':rec.winner===i?'win':'loss';return{id:`${rec.id}:${p.userId}:${LEADERBOARD_ID}`,contestId:rec.id,userId:p.userId,event:rec.setup.sport,leaderboardId:LEADERBOARD_ID,policyId:rec.setup.policy.id,delta:rec.setup.policy[outcome],outcome,createdAt:rec.setup.createdAt};});}
export function standings(state:SavedState,event?:Sport){const rows=USERS.map(user=>{const ledger=state.ledger.filter(a=>a.userId===user.id&&(!event||a.event===event));return{user,points:ledger.reduce((n,a)=>n+a.delta,0),played:ledger.filter(a=>!a.reverses).length,wins:ledger.filter(a=>a.outcome==='win'&&!a.reverses).length,draws:ledger.filter(a=>a.outcome==='draw'&&!a.reverses).length,losses:ledger.filter(a=>a.outcome==='loss'&&!a.reverses).length,rank:0};}).sort((a,b)=>b.points-a.points||a.user.id.localeCompare(b.user.id));return rows.map((row,i)=>({...row,rank:rows.findIndex(r=>r.points===row.points)+1}));}
export function completedEntry(state:SavedState,id:string){return state.recordings.find(r=>r.setup.entryId===id&&r.setup.mode==='ranked');}
export function rankedPlayed(state:SavedState,userId:string){return state.recordings.filter(r=>r.setup.mode==='ranked'&&r.setup.participants.some(p=>p.userId===userId)).length;}
export function availableEntry(state:SavedState,userId:string,sport:Sport):Entry|undefined {if(!state.policy.rankedEnabled||rankedPlayed(state,userId)>=state.policy.allowance)return;return SCHEDULE.find(e=>e.users.includes(userId)&&e.sport===sport&&!completedEntry(state,e.id)&&e.users.every(id=>rankedPlayed(state,id)<state.policy.allowance));}
export function emptyState():SavedState{return{version:1,recordings:[],ledger:[],policy:{...DEFAULT_POLICY},active:null,imports:[],revision:0};}
export function fixtures():SavedState{const state=emptyState();for(const [i,entry] of SCHEDULE.filter(e=>e.sport==='basketball').entries()){const setup:Setup={id:`demo-${entry.id}`,seed:entry.seed,sport:entry.sport,participants:entry.users.map((userId,j)=>({userId,copyId:COPIES.find(c=>c.userId===userId&&c.cardId===CARDS[(i+j)%2].id)!.id,cardId:CARDS[(i+j)%2].id,strategy:'steady'})) as Setup['participants'],mode:'ranked',tie:'draw',secret:false,showcase:false,entryId:entry.id,policy:{...DEFAULT_POLICY},rulesVersion:RULES_VERSION,createdAt:'2026-09-08T18:00:00.000Z'};const recording=simulate(setup);state.recordings.push(recording);state.ledger.push(...awardsFor(recording));}return state;}
function assertState(s:SavedState){if(s.version!==1||!Array.isArray(s.recordings)||!Array.isArray(s.ledger))throw Error('This save has an unsupported format. Export it before resetting.');if(new Set(s.ledger.map(a=>a.id)).size!==s.ledger.length)throw Error('Duplicate points awards in save.');return s;}
function envelope(state:SavedState){const payload=JSON.stringify(state);return JSON.stringify({payload,checksum:hash(payload)});}
function decode(text:string){const e=JSON.parse(text);if(hash(e.payload)!==e.checksum)throw Error('The local save did not pass its integrity check.');return assertState(JSON.parse(e.payload));}
export class LocalArenaRepository implements ArenaRepository {
 private storage:Storage;
 constructor(storage:Storage){this.storage=storage;}
 load(){const raw=this.storage.getItem(STORAGE_KEY),pending=this.storage.getItem(STORAGE_KEY+':journal');let s=raw?decode(raw):fixtures();if(pending){const staged=decode(pending);if(staged.revision>s.revision){this.storage.setItem(STORAGE_KEY,pending);s=staged;}this.storage.removeItem(STORAGE_KEY+':journal');}return s;}
 private write(state:SavedState){state.revision++;const text=envelope(state);this.storage.setItem(STORAGE_KEY+':journal',text);this.storage.setItem(STORAGE_KEY,text);this.storage.removeItem(STORAGE_KEY+':journal');return state;}
 private async lock<T>(fn:()=>T):Promise<T>{if(typeof navigator!=='undefined'&&navigator.locks)return navigator.locks.request(STORAGE_KEY,async()=>fn());return fn();}
 async commit(setup:Setup){return this.lock(()=>{const state=this.load();const existing=state.recordings.find(r=>r.id===setup.id||(setup.mode==='ranked'&&r.setup.entryId===setup.entryId));if(existing)return{recording:existing,state,existing:true};
  if(setup.participants[0].userId===setup.participants[1].userId)throw Error('Choose two different demo users.');
  for(const p of setup.participants){if(!COPIES.some(c=>c.id===p.copyId&&c.cardId===p.cardId&&c.userId===p.userId))throw Error('That card copy is not in this user’s collection.');}
  if(setup.mode==='ranked'){const entry=SCHEDULE.find(e=>e.id===setup.entryId);if(!entry||!state.policy.rankedEnabled)throw Error('This ranked entry is unavailable.');if(entry.sport!==setup.sport||entry.seed!==setup.seed||entry.users.some((id,i)=>id!==setup.participants[i].userId))throw Error('Ranked opponent, order, sport, and seed must match the schedule.');if(entry.users.some(id=>rankedPlayed(state,id)>=state.policy.allowance))throw Error('A competitor has used their ranked allowance. Exhibition is still available.');if(JSON.stringify(setup.policy)!==JSON.stringify(state.policy))throw Error('Scoring policy changed. Review the setup again.');if(setup.secret)throw Error('Secret stage effects are exhibition only in the prototype ranked policy.');}
  const recording=simulate(structuredClone(setup));const problems=validateRecording(recording);if(problems.length)throw Error(problems.join('; '));state.recordings.push(recording);state.ledger.push(...awardsFor(recording));state.active={id:recording.id,time:0};this.write(state);return{recording,state,existing:false};});}
 savePlayback(id:string,time:number){const state=this.load();const rec=state.recordings.find(r=>r.id===id);if(!rec)return;state.active=time>=completionTime(rec)?null:{id,time:Math.min(rec.duration,Math.max(0,time))};this.write(state);}
 async updatePolicy(policy:Policy){return this.lock(()=>{for(const n of [policy.win,policy.draw,policy.loss,policy.allowance])if(!Number.isInteger(n)||n<0||n>100)throw Error('Use whole numbers from 0 to 100.');const state=this.load();state.policy={...policy,id:`club-points-${hash(JSON.stringify(policy))}`};return this.write(state);});}
 async saveAssets(asset:AssetManifest){return this.lock(()=>{const state=this.load();state.imports=[...state.imports.filter(a=>a.cardId!==asset.cardId),asset];return this.write(state);});}
 async reset(){return this.lock(()=>{const state=fixtures();state.revision=this.load().revision;return this.write(state);});}
}
export function adjustAward(state:SavedState,originalId:string,delta:number,correctionId:string):SavedState{const next=structuredClone(state),original=next.ledger.find(a=>a.id===originalId);if(!original)throw Error('Original award not found.');if(!Number.isInteger(delta))throw Error('Correction must use integer points.');if(next.ledger.some(a=>a.id===correctionId))return next;next.ledger.push({...original,id:correctionId,delta,reverses:originalId,createdAt:new Date().toISOString()});return next;}

